config/routes.rb
Mk1::Application.routes.draw do
  devise_for :users

  resources :photos

  get "store/index"
  get "store/things_new"
  get "store/things_fancy"

  resources :products
  resources :review_photos

  root :to => 'store#index', :as => 'store'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :product_id, :photofile
  belongs_to :product
  has_attached_file :photofile, :styles => {:nomal => "400x400>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :photos, :review_photos, :author, :buy_link, :description, :images, :like_num, :name, :own_num, :price, :status, :subtitle
  has_many :photos
  has_many :review_photos
end

app/models/review_photo.rb
class ReviewPhoto < ActiveRecord::Base
  attr_accessible :product_id, :photofile
  belongs_to :product
  has_attached_file :photofile, :styles => {:nomal => "400x400>", :thumb => "100x100>"}, :default_url => "/images/:style/missing.png"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @photos }
    end
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
    @photo = Photo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @photo = Photo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(params[:photo])

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render json: @photo, status: :created, location: @photo }
      else
        format.html { render action: "new" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @photo = Photo.find(params[:id])

    respond_to do |format|
      if @photo.update_attributes(params[:photo])
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo = Photo.find(params[:id])
    @photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to :id=>@product.id,:action=>'edit',notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/review_photos_controller.rb
class ReviewPhotosController < ApplicationController
  def show
    @review_photo = ReviewPhoto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review_photo }
    end
  end

  # GET /photos/new
  # GET /photos/new.json
  def new
    @review_photo = ReviewPhoto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review_photo }
    end
  end

  # GET /photos/1/edit
  def edit
    @review_photo = ReviewPhoto.find(params[:id])
  end

  def create
    @review_photo = ReviewPhoto.new(params[:review_photo])

    respond_to do |format|
      if @review_photo.save
        format.html { redirect_to @review_photo, notice: 'ReviewPhoto was successfully created.' }
        format.json { render json: @review_photo, status: :created, location: @review_photo }
      else
        format.html { render action: "new" }
        format.json { render json: @review_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /photos/1
  # PUT /photos/1.json
  def update
    @review_photo = ReviewPhoto.find(params[:id])

    respond_to do |format|
      if @review_photo.update_attributes(params[:review_photo])
        format.html { redirect_to @review_photo, notice: 'ReviewPhoto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @review_photo = ReviewPhoto.find(params[:id])
    @review_photo.destroy

    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  	#@products = Product.all
    @products = Product.paginate(:page => params[:page],:per_page => 4)
  end
  def things_new
    @filter = :things_new     #bug
    @products = Product.order('products.created_at DESC').limit(10)
    render :action => "things"
  end

  def things_fancy
    @filter = :things_fancy       #bug
    @products = Product.order('products.like_num DESC').limit(10)
    render :action => "things"

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/review_photos_helper.rb
module ReviewPhotosHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MomKids就是麦奇智</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%=	 stylesheet_link_tag "bootstrap", :media => "all" %>
  <%= javascript_include_tag :default %>

  <%= csrf_meta_tags %>
  <script src="http://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
</head>
<title>Momkis 麦奇智母婴</title>
<header>
	<nav class="navbar navbar-fixed-top">
		<div class="navbar-inner">
			<a href="/" class="brand"><img alt="Momkids" src="/assets/logos/11-035f9359dd3f73f844eb8ae0ddb8ca75.png">Momkids</a>
			<ul class="nav pull-left">
				<li class="nav_things dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-th"></i><span>发现</span><i class="icon-caret-down"></i></a>
					<ul class="dropdown-menu">
						<li><a href="/store/things_new"><i class="icon-rocket"></i>最新</a></li>
						<li><a href="/store/things_fancy"><i class="icon-bullseye"></i>喜爱</a></li>

					</ul>
				</li>
				


				<li class="nav_help dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="icon-tint"></i><span>关于我们</span><i class="icon-caret-down"></i></a>
					<ul class="dropdown-menu">
						<li><a href="http://weibo.com/momkids"><i class="icon-weibo"></i>微博</a></li>
						<li><a href="/tucao"><i class="icon-leaf"></i>吐槽</a></li>
						<li><a href="mailto:hello@momkids.com"><i class="icon-envelope"></i>邮件</a></li>
					</ul>
				</li>
				<li class="nav_new_thing">
					<%= link_to  new_product_path do %>
						<i class="icon-magic"></i>新建产品
					<% end %>

				</li>


			</ul>
            <form accept-charset="UTF-8" action="/search" class="navbar-search pull-right" id="nav_search" method="get">
                <div style="margin:0;padding:0;display:inline"><input name="utf8" type="hidden" value="?"></div>
                <input class="search-query span2" name="q" type="search"><i class="icon-search"></i>
            </form>
				<ul class="nav pull-right">
                  <% if user_signed_in? -%> <!-- Provided by devise -->
                      <div class = "signin_tip">
                        <%= current_user.email %> |
                        <%= link_to '用户信息', edit_user_registration_path %> |
                        <%= link_to '退出登录', destroy_user_session_path, :method => :delete %> |
                      </div>
                  <% end -%>
                  <% unless user_signed_in? -%>
                      <div class="signin_tip">
                        <%= link_to '注册', new_user_registration_path %> |
                        <%= link_to '登录', new_user_session_path %>
                      </div>
                  <% end -%>
<!--
					<li class="signin_tip">评论登录:</li>

					<li class="signin"><div class="ds-login"></div></li>
-->

				</ul>

		</div>
	</nav>
  <script>var duoshuoQuery = {short_name:"momkids"};</script>
  <script src="http://static.duoshuo.com/embed.js"></script>
</header>

<body>


<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/_new_photo.html.erb
<p>添加走马灯照片</p>
<%= form_for(photo, :class=>"form-horizontal") do |f|%>

    <div class="control-group">
      <!--<%= f.label :product_id, :class=>"control-label" %>-->
      <div class="controls">
        <%= f.hidden_field :product_id %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Upload Image</label>
      <div class="controls">
        <%= f.file_field :photofile %>
      </div>
    </div>

    <div class="control-group">
      <%=	 f.submit "添加", :class=>"btn"%>
    </div>
<%end%>

app/views/photos/_photo_list.html.erb
<p>走马灯照片</p>
<table class="table">
  <thead>
    <tr>
      <th>Thumb</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <% photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.photofile.url(:thumb) %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<h1>Listing photos</h1>

<table>
  <tr>
    <th>Product</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @photos.each do |photo| %>
  <tr>
    <td><%= photo.product_id %></td>
    <td><%= link_to 'Show', photo %></td>
    <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
    <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New photo</h1>

<%= render 'form' %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= image_tag(@photo.photofile.url) %>
</p>



<%= link_to '删除', @photo, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to '回到产品编辑', edit_product_path(@photo.product_id) %>

app/views/products/_form.html.erb
<%=	 javascript_include_tag "jquery.qeditor" %>
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
   <div class="span5">
      <div class="field">
        <%= f.label :name %>    <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
      </div>
      <div class="field">
        <%= f.label :status %>
        <%= f.text_field :status %>
      </div>
      <div class="field">
        <%= f.label :price %>
        <%= f.text_field :price %>
      </div>
   </div>
   <div class="span4">
      <div class="field">
        <%= f.label :buy_link %>
        <%= f.text_field :buy_link %>
      </div>

      <div class="field">
        <%= f.label :like_num %>
        <%= f.number_field :like_num %>
      </div>
      <div class="field">
        <%= f.label :own_num %>
        <%= f.number_field :own_num %>
      </div>
      <div class="field">
        <%= f.label :author %>
        <%= f.text_field :author %>
      </div>
   </div>
  <div class="field span10">
    <p><%= f.label :description, :display => "block" %><br/>  </p>
    <%= f.text_area :description%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

<script type="text/javascript">
    $("#product_description").qeditor({});
</script>

app/views/products/edit.html.erb
<h1 class="text-center">产品编辑</h1>
<div class="container">
    <div class="row">
      <div class="span10">
        <%= render 'form' %>

        <div class="row">
          <div class="span5 control-group">
            <%= render :partial => 'photos/photo_list', :locals=>{:photos=> @product.photos} %>

            <%=	 render :partial => 'photos/new_photo', :locals => {:photo => Photo.new(:product_id =>@product.id)} %>
          </div>
          <div class="span5 control-group">
            <%= render :partial => 'review_photos/review_photo_list', :locals=>{:review_photos=>@product.review_photos} %>
            <%= render :partial => 'review_photos/new_review_photo', :locals => {:rp=>ReviewPhoto.new(:product_id =>@product.id)} %>

          </div>
        </div>
       <%= link_to 'Show', @product %> |
       <%= link_to 'Back', products_path %>

      </div>
    </div>
</div>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Subtitle</th>
    <th>Status</th>
    <th>Price</th>
    <th>Buy link</th>
    <th>Images</th>
    <th>Like num</th>
    <th>Own num</th>
    <th>Author</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.name %></td>
    <td><%= product.subtitle %></td>
    <td><%= product.status %></td>
    <td><%= product.price %></td>
    <td><%= product.buy_link %></td>
    <td><%= product.images %></td>
    <td><%= product.like_num %></td>
    <td><%= product.own_num %></td>
    <td><%= product.author %></td>
    <td><%= product.description %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

Dump for seed.rb
<% @products.each do |product| %>
    product.create(:name =><%= product.name %>,
        :subtitle =><%= product.subtitle %>,
        :status =><%= product.status %> ,
        :price =><%= product.price %>,
        :buy_link =>  <%= product.buy_link %>,
        :images => <%= product.images %>,
        :like_num =><%= product.like_num %>,
        :own_num =><%= product.own_num %>,
        :author=><%= product.author %>,
        :description =%{<%= product.description %>})
<% end %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/review_photos/_form.html.erb
<%= form_for(@review_photo) do |f| %>
  <% if @review_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review_photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @review_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/review_photos/_new_review_photo.html.erb
<h4>添加Review照片</h4>
<%= form_for(rp, :class=>"form-horizontal") do |f|%>

    <div class="control-group">
      <!--<%= f.label :product_id, :class=>"control-label" %>-->
      <div class="controls">
        <%= f.hidden_field :product_id%>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Upload Image</label>
      <div class="controls">
        <%= f.file_field :photofile %>
      </div>
    </div>

    <div class="control-group">
      <%=	 f.submit "添加", :class=>"btn"%>
    </div>
<%end%>

app/views/review_photos/_review_photo_list.html.erb
<h4>Review照片</h4>
<table class="table">
  <thead>
  <tr>
    <th>Thumb</th>
    <th>右键获取照片URL</th>
    <th>Edit</th>
    <th>Destroy</th>
  </tr>
  </thead>

  <% review_photos.each do |photo| %>
      <tr>
        <td><%= image_tag photo.photofile.url(:thumb) %></td>
        <td><%= link_to 'URL', photo.photofile.url(:nomal) %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
</table>

app/views/review_photos/edit.html.erb
<h1>Editing photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @review_photo %> |

app/views/review_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= image_tag(@review_photo.photofile.url) %>
</p>



<%= link_to '删除', @review_photo, method: :delete, data: { confirm: 'Are you sure?' } %>|
<%= link_to '回到产品编辑', edit_product_path(@review_photo.product_id) %>

app/views/store/index.html.erb
<% if notice %>
<p id = "notice"> <%= notice %> </p>
<% end %>


 <section class="container-fluid">
	<div class="home_wrapper">
		<header id="home_welcome"><h2><i class="icon-road"></i>优雅母婴生活</h2></header>
		<section id="home_things">
		<ul>

<% @products.each do |product| %>
		<li class="thing">
			<div class="pre_ribbon stock"><span><%=product.status%></span></div>
			<%= link_to(product) do %>
              <%if product.photos.count !=0 then %>
				<%= image_tag(product.photos[0].photofile.url(:nomal)) %>
              <%end %>
			<% end %>
			
			<h4 data-placement="bottom" data-toggle="tooltip" title="" data-original-title="<%=product.name%>"><%=product.name%></h4><p><span class="fanciers"><i class="icon-heart"></i><span class="fanciers_count"><%=product.like_num%></span></span><span class="owners"><i class="icon-check"></i><span class="owners_count"><%=product.own_num%></span></span><span class="reviews_count"><i class="icon-book"></i>0</span><small>¥ <%=product.price%></small></p>
		</li>
<% end %>

		</ul>
<div class="digg_pagination span6">
  <%= will_paginate @products %>
</div>
		</section>


<aside id="home_news">
<div class="wrapper">
<h4>最新<a href="/things"><i class="icon-double-angle-right icon-large"></i></a></h4>
	<ul id="home_new_things">

<% @products[0..3].each do |product| %>
		<li class="thing">
			<%= link_to(product) do %>
              <%if product.photos.count !=0 then %>
				<%= image_tag(product.photos[0].photofile.url(:nomal)) %>

              <% end %>
            <% end %>
			<h4 data-placement="bottom" data-toggle="tooltip" title="" data-original-title="<%=product.name%>"><%=product.name%></h4><p><span class="fanciers"><i class="icon-heart"></i><span class="fanciers_count"><%=product.like_num%></span></span>
			</p>
		</li>
<% end %>

	</ul>

<h4>最新评论</h4>
	<ul id="home_new_reviews">	</ul>
  <ul class="ds-recent-comments" data-num-items="5" data-show-avatars="0" data-show-time="1" data-excerpt-length="20"></ul>
</div>
	<div id="site_filling"><small>粤ICP备88888号</small></div>
</aside>
   </div>
</section>

app/views/store/things.html.erb
<section class="container-fluid">
  <div class="things_wrapper">
    <section id="things_index">
      <nav class="btn-group">
        <a href="/store/things_new" class="btn <%=if @filter == :things_new then 'active' end %>"><i class="icon-rocket"></i>最新</a>
        <a href="/store/things_fancy" class="btn <%=if @filter == :things_fancy then 'active' end%>"><i class="icon-bullseye"></i>喜爱</a>

      </nav>
      <ul>
        <% @products.each do |product| %>
            <li class="thing">
              <div class="pre_ribbon stock"><span><%= product.status %></span></div>
              <%= link_to(product) do %>
                  <% if product.photos.count !=0 then %>
                      <%= image_tag(product.photos[0].photofile.url(:nomal)) %>
                  <% end %>
              <% end %>

              <h4 data-placement="bottom" data-toggle="tooltip" title="" data-original-title="<%= product.name %>"><%= product.name %></h4>

              <p>
                <span class="fanciers">
                  <i class="icon-heart"></i>
                  <span class="fanciers_count"><%= product.like_num %></span>
                </span>
                <span class="owners"><i class="icon-check"></i><span class="owners_count"><%= product.own_num %></span></span><span class="reviews_count"><i class="icon-book"></i>0</span>
                <small>¥ <%= product.price %></small>
              </p>
            </li>
        <% end %>
      </ul>
    </section>
  </div>
</section>